/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_rmd2k_guitarstudio_android_Tools_Tuner_FFT */

#ifndef _Included_com_example_rmd2k_guitarstudio_android_Tools_Tuner_FFT
#define _Included_com_example_rmd2k_guitarstudio_android_Tools_Tuner_FFT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_rmd2k_guitarstudio_android_Tools_Tuner_FFT
 * Method:    fft
 * Signature: ([S)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_rmd2k_guitarstudio_1android_Tools_Tuner_FFT_fft
  (JNIEnv *, jclass, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
